apiVersion: v1
kind: Namespace
metadata:
  name: databot-v4
  labels:
    app.kubernetes.io/name: databot
    app.kubernetes.io/version: v4
    app.kubernetes.io/component: platform
    app.kubernetes.io/managed-by: kustomize
    environment: production
    project: databot
    tier: application
    # Labels pour la sécurité et le monitoring
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    app.kubernetes.io/maintainer: "DATA_BOT DevOps Team"
    app.kubernetes.io/description: "Namespace pour l'application DATA_BOT v4"
    scheduler.alpha.kubernetes.io/preferAvoidPodsWithNodeLabels: "true"
    # Annotations pour la gestion des coûts
    cost-center: "engineering"
    project-id: "databot-v4"
    owner: "devops-team"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: databot-quota
  namespace: databot-v4
  labels:
    app.kubernetes.io/name: databot
    app.kubernetes.io/component: quota
spec:
  hard:
    # Limites de ressources computationnelles
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    
    # Limites de stockage
    requests.storage: 200Gi
    persistentvolumeclaims: "15"
    
    # Limites d'objets Kubernetes
    pods: "50"
    services: "20"
    secrets: "15"
    configmaps: "10"
    deployments.apps: "10"
    statefulsets.apps: "5"
    jobs.batch: "10"
    cronjobs.batch: "5"
    
    # Limites réseau
    services.loadbalancers: "2"
    services.nodeports: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: databot-limits
  namespace: databot-v4
  labels:
    app.kubernetes.io/name: databot
    app.kubernetes.io/component: limits
spec:
  limits:
  # Limites par conteneur
  - type: Container
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 50m
      memory: 64Mi
    maxLimitRequestRatio:
      cpu: 4
      memory: 8
  
  # Limites par Pod
  - type: Pod
    max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 100m
      memory: 128Mi
  
  # Limites par PVC
  - type: PersistentVolumeClaim
    max:
      storage: 100Gi
    min:
      storage: 1Gi